from dotenv import load_dotenv as __load_dotenv

import os

__load_dotenv()

MONGO_USERNAME = os.getenv('MONGO_USERNAME')
MONGO_PASSWORD = os.getenv('MONGO_PASSWORD')
MONGO_HOST = os.getenv('MONGO_HOST')
MONGO_PORT = os.getenv('MONGO_PORT')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME')

MYSQL_USERNAME = os.getenv('MYSQL_USERNAME')
MYSQL_PASSWORD = os.getenv('MYSQL_PASSWORD')
MYSQL_HOST = os.getenv('MYSQL_HOST')
MYSQL_PORT = os.getenv('MYSQL_PORT')
MYSQL_DB_NAME = os.getenv('MYSQL_DB_NAME')

MYSQL_HOST_SECOND_DB = os.getenv('MYSQL_HOST_SECOND_DB')
MYSQL_PORT_SECOND_DB = os.getenv('MYSQL_PORT_SECOND_DB')
MYSQL_USERNAME_SECOND_DB = os.getenv('MYSQL_USERNAME_SECOND_DB')
MYSQL_PASSWORD_SECOND_DB = os.getenv('MYSQL_PASSWORD_SECOND_DB')
MYSQL_DB_NAME_SECOND_DB = os.getenv('MYSQL_DB_NAME_SECOND_DB')

TIKTOK_MS_TOKEN = os.getenv('TIKTOK_MS_TOKEN')

TWITTER_USERNAME_1 = os.getenv('TWITTER_USERNAME1')
TWITTER_PASSWORD_1 = os.getenv('TWITTER_PASSWORD1')

TWITTER_USERNAME_2 = os.getenv('TWITTER_USERNAME2')
TWITTER_PASSWORD_2 = os.getenv('TWITTER_PASSWORD2')
